### ISSUE TITLE
swmod and screen

### ISSUE THREAD

**Issue by vonsturm** [oschulz/swmod#4]
If you load software using swmod and then you open a new shell using screen from within the previous one the program results still loaded but the LD_LIBRARY_PATH results cleaned. Thus you get errors while loading shared libraries but are unable to reload the paths. For example:

$ swmod load gerda@master
$ screen -S test
$ Raw2MGDO ...
> error while loading shared libraries

$ swmod load gerda@master

> already loaded

**Comment by oschulz** [comment]
Unfortunately, this hard to unavoid: LD_LIBRARY_PATH is always cleared in a `screen` environment (see https://superuser.com/questions/235760/ld-library-path-unset-by-screen). It's best to run swmod inside of `screen`.

**Comment by vonsturm** [comment]
> It's best to run swmod inside of screen.

That's what I was doing... so ok I'll need to stick to that. Thanks!
